[package]
name = "chip"
version = "0.1.0"
edition.workspace = true
authors.workspace = true
rust-version.workspace = true

[dependencies]
color-eyre = { workspace = true }
strum_macros = { workspace = true }
strum = { workspace = true }
