[workspace]
members = [
    "./cpu",
    "./c64basic",
    "./disassembler",
    "./convertprg",
    "./irq",
    "./handasm",
    "./assemble",
    "./assembler",
    "./chip",
]
default-members = [
    "./cpu",
    "./c64basic",
    "./disassembler",
    "./convertprg",
    "./irq",
    "./handasm",
    "./assemble",
    "./assembler",
    "./chip",
]

[profile.test]
opt-level = 3

[profile.bench]
debug = true

[workspace.dependencies]
clap = { version = "~4.0", features = ["derive", "wrap_help"] }
color-eyre = { version = "0.6.2", default-features = false }
lazy_static = "1.4.0"
rand = "0.8.5"
regex = "1"
strum_macros = "0.24.1"
strum = "0.24.1"
thiserror = "1.0.37"

[workspace.package]
edition = "2021"
rust-version = "1.65"
authors = ["James Chacon <chacon.james@gmail.com>"]

[package]
name = "rusty6502"
version = "0.1.0"
edition.workspace = true
authors.workspace = true
rust-version.workspace = true

[dependencies]
memory = { path = "./memory", version = "~0.1" }
cpu = { path = "./cpu", version = "~0.1" }
chip = { path = "./chip", version = "~0.1" }
