[workspace]
members = [
    "./c64basic",
    "./disassemble",
    "./disassembler",
    "./convertprg",
    "./irq",
    "./handasm",
    "./assemble",
]
default-members = [
    "./c64basic",
    "./disassemble",
    "./disassembler",
    "./convertprg",
    "./irq",
    "./handasm",
    "./assemble",
]

[package]
name = "rusty6502"
version = "0.1.0"
edition = "2021"

[dependencies]
memory = { path = "./memory", version = "~0.1" }
cpu = { path = "./cpu", version = "~0.1" }
