[package]
edition = "2021"
name    = "cpu"
version = "0.1.0"

[dependencies]
strum_macros = "0.24.1"
strum = "0.24.1"
lazy_static = "1.4.0"
color-eyre = { version = "0.6.2", default-features = false }
memory  = { path = "../memory", version = "~0.1" }
rand = "0.8.5"
thiserror = "1.0.37"
