[package]
name = "handasm"
version = "0.1.0"
edition.workspace = true
authors.workspace = true
rust-version.workspace = true

[dependencies]
clap = { workspace = true }
color-eyre = { workspace = true }
proc-macro2 = { workspace = true }
