[package]
name = "assembler"
version = "0.1.0"
edition = "2021"

[dependencies]
assemble = { path = "../assemble", version = "~0.1" }
color-eyre = { version = "0.6.2", default-features = false }
clap = { version = "3.2.16", features = ["derive"] }