[package]
edition = "2021"
name    = "assemble"
version = "0.1.0"

[dependencies]
rusty6502  = { path = "../", version = "~0.1" }
color-eyre = { workspace = true }
regex = { workspace = true }
lazy_static = { workspace = true }