[package]
name    = "assemble"
version = "0.1.0"
edition.workspace = true
authors.workspace = true
rust-version.workspace = true

[dependencies]
rusty6502  = { path = "../", version = "~0.1" }
color-eyre = { workspace = true }
regex = { workspace = true }
lazy_static = { workspace = true }