[package]
name = "apu"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
authors.workspace = true

[dependencies]
chip = { workspace = true }
color-eyre = { workspace = true }
memory = { workspace = true }
