[package]
name = "monitor_tui"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
authors.workspace = true

[dependencies]
clap = { workspace = true }
clap-num = { workspace = true }
color-eyre = { workspace = true }
monitor = { workspace = true }
