[package]
name = "disassembler"
version = "0.1.0"
edition = "2021"

[dependencies]
disassemble = { path = "../disassemble", version = "~0.1" }
rusty6502 = { path = "../", version = "~0.1" }
gflags = "0.3"