[package]
name = "c64basic"
version = "0.1.0"
edition.workspace = true
authors.workspace = true
rust-version.workspace = true

[dependencies]
rusty6502 = { workspace = true }

color-eyre = { workspace = true }
strum_macros = { workspace = true }
strum = { workspace = true }
