[package]
name = "c64basic"
version = "0.1.0"
edition.workspace = true
authors.workspace = true
rust-version.workspace = true

[dependencies]
rusty6502 = { path = "../", version = "~0.1" }
strum_macros = { workspace = true }
strum = { workspace = true }
lazy_static = { workspace = true }
